// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.continuent.tungsten.replicator.extractor.drizzle.messages;

public final class SchemaMessage {
  private SchemaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Schema extends
      com.google.protobuf.GeneratedMessage {
    // Use Schema.newBuilder() to construct.
    private Schema() {}
    
    private static final Schema defaultInstance = new Schema();
    public static Schema getDefaultInstance() {
      return defaultInstance;
    }
    
    public Schema getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.internal_static_drizzled_message_Schema_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.internal_static_drizzled_message_Schema_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string collation = 2;
    public static final int COLLATION_FIELD_NUMBER = 2;
    private boolean hasCollation;
    private java.lang.String collation_ = "";
    public boolean hasCollation() { return hasCollation; }
    public java.lang.String getCollation() { return collation_; }
    
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasCollation()) {
        output.writeString(2, getCollation());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasCollation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getCollation());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema result;
      
      // Construct using com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema();
        return builder;
      }
      
      protected com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema.getDescriptor();
      }
      
      public com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema getDefaultInstanceForType() {
        return com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema) {
          return mergeFrom((com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema other) {
        if (other == com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasCollation()) {
          setCollation(other.getCollation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 18: {
              setCollation(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string collation = 2;
      public boolean hasCollation() {
        return result.hasCollation();
      }
      public java.lang.String getCollation() {
        return result.getCollation();
      }
      public Builder setCollation(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCollation = true;
        result.collation_ = value;
        return this;
      }
      public Builder clearCollation() {
        result.hasCollation = false;
        result.collation_ = getDefaultInstance().getCollation();
        return this;
      }
    }
    
    static {
      com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.getDescriptor();
    }
    
    static {
      com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_drizzled_message_Schema_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_drizzled_message_Schema_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\020drizzled.message\")\n\006Sche" +
      "ma\022\014\n\004name\030\001 \002(\t\022\021\n\tcollation\030\002 \001(\tBP\n=c" +
      "om.continuent.tungsten.replicator.extrac" +
      "tor.drizzle.messagesB\rSchemaMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_drizzled_message_Schema_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_drizzled_message_Schema_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_drizzled_message_Schema_descriptor,
              new java.lang.String[] { "Name", "Collation", },
              com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema.class,
              com.continuent.tungsten.replicator.extractor.drizzle.messages.SchemaMessage.Schema.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
